server:
  port: 8091

spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      healthcheck:
        enabled: true
  instance:
    hostname: "localhost"
