server:
  port: ${PORT:5000}

spring:
  application:
    name: eureka

eureka:
  password: Eureka1234
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://psinder-eureka:5000/eureka/
      healthcheck:
        enabled: true
  instance:
    hostname: localhost