server:
  port: 8091

spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
      healthcheck:
        enabled: true
  instance:
    hostname: "localhost"