server:
  port: ${PORT:5000}

spring:
  application:
    name: eureka

eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        password: ${EUREKA_USER_PASSWORD:password}
      healthcheck:
        enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
ribbon:
  eureka:
    enabled: false
  ServerListRefreshInterval: 15000