server:
  port: ${PORT:5000}

spring:
  application:
    name: eureka

eureka:
  password: ${EUREKA_USER_PASSWORD:password}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      healthcheck:
        enabled: true
  instance:
    hostname: localhost