server:
  port: ${PORT:5000}

spring:
  application:
    name: eureka

security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}

ribbon:
  eureka:
    enabled: false
  ServerListRefreshInterval: 15000